name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      # - name: Test
      #   run: dotnet test --no-build --verbosity normal
      - name: Publish
        run: dotnet publish -c Release -r win-x64 -o ./publish sensors2metrics/sensors2metrics.csproj
      - name: Publish Self-Contained
        run: dotnet publish -c Release -r win-x64 --self-contained -o ./publish-sc sensors2metrics/sensors2metrics.csproj
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sensors2metrics
          path: ./publish
      - name: Upload Artifact Self-Contained
        uses: actions/upload-artifact@v4
        with:
          name: sensors2metrics-self-contained
          path: ./publish-sc
